import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'kn' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  getLocale: () => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    home: 'Home',
    firstAid: 'First Aid',
    sos: 'SOS',
    profile: 'Profile',
    contacts: 'Contacts',
    settings: 'Settings',
    emergencyResponse: 'Emergency Response',
    quickResponse: 'Emergency Response',
    whatSituation: 'What is the situation?',
    medicalProfile: 'Medical Profile',
    healthRecords: 'Your health records',
    sosPanel: 'SOS PANEL',
    assistanceNeeded: 'Immediate Assistance Needed?',
    callAmbulance: 'Ambulance',
    callPolice: 'Police',
    callFire: 'Fire Force',
    shareLocation: 'Share Location',
    sendAlert: 'Send Alert',
    emergencyTips: 'Emergency Tips',
    criticalWarnings: 'CRITICAL WARNINGS',
    readAloud: 'READ ALOUD',
    stop: 'STOP',
    saveProfile: 'Save Profile',
    bloodGroup: 'Blood Group',
    allergies: 'Allergies',
    medications: 'Medications',
    conditions: 'Medical Conditions',
    language: 'Language',
    darkMode: 'Dark Mode',
    voiceAssistance: 'Voice Assistance',
    notifications: 'Notifications',
    restart: 'RESTART',
    firstAidGuide: 'First Aid Guide',
    selectCategory: 'Select a category for instructions',
    steps: 'Steps',
    holdToAlert: 'Hold to alert',
    profileSub: 'Vital info for first responders',
    personalDetails: 'Personal Details',
    fullName: 'Full Name',
    dob: 'Date of Birth',
    medicalInfo: 'Medical Information',
    securityMessage: 'Data is encrypted and stored locally on your device only.',
    emergencyHelp: 'Emergency Help',
    emergencyHelpSub: 'Press the SOS button on the bottom bar for immediate assistance or visit the SOS panel to call authorities.',
    profileSaved: 'Profile saved successfully',
    emergencyStored: 'Emergency medical information is now stored locally.',
    holdToAlertSub: 'Hold to alert',
    addContact: 'Add Emergency Contact',
    addContactSub: 'Input the details of someone who can help you in an emergency.',
    relation: 'Relation',
    phoneNumber: 'Phone Number',
    saveContact: 'SAVE CONTACT',
    noContacts: 'No emergency contacts yet. Add your first contact to stay safe.',
    contactsSub: 'Emergency help list',
    calling: 'Calling',
    messaging: 'Messaging',
    contactAdded: 'Contact added successfully.',
    contactRemoved: 'Contact removed.',
    namePhoneRequired: 'Please provide both name and phone number.',
    // First Aid Titles
    'title.bleeding': 'Bleeding',
    'title.burns': 'Burns',
    'title.fractures': 'Fractures',
    'title.cpr': 'CPR',
    'title.choking': 'Choking',
    'title.snake-bite': 'Snake Bite',
    // Bleeding
    'bleeding.step1': 'Stay calm and wear gloves if available.',
    'bleeding.step2': 'Apply direct pressure using clean cloth or bandage.',
    'bleeding.step3': 'Raise injured area above heart level if possible.',
    'bleeding.step4': 'Do not remove soaked bandages, add another layer.',
    'bleeding.step5': 'Call emergency services if bleeding continues.',
    // Burns
    'burns.step1': 'Move away from heat source.',
    'burns.step2': 'Cool burn under running water for 20 minutes.',
    'burns.step3': 'Remove tight jewelry carefully.',
    'burns.step4': 'Cover with sterile non-stick dressing.',
    'burns.step5': 'Do not apply ice, butter, or toothpaste.',
    // CPR
    'cpr.step1': 'Check responsiveness.',
    'cpr.step2': 'Call emergency services.',
    'cpr.step3': 'Place hands in center of chest.',
    'cpr.step4': 'Push hard and fast, 100 to 120 compressions per minute.',
    'cpr.step5': 'Continue until help arrives.',
    // Fractures
    'fractures.step1': 'Do not move the injured person unless necessary.',
    'fractures.step2': 'Stop any bleeding by applying pressure.',
    'fractures.step3': 'Immobilize the area with a splint if possible.',
    'fractures.step4': 'Apply ice packs to limit swelling.',
    'fractures.step5': 'Seek professional medical help immediately.',
    // Choking
    'choking.step1': 'Encourage them to cough.',
    'choking.step2': 'Give 5 back blows between shoulder blades.',
    'choking.step3': 'Give 5 abdominal thrusts (Heimlich maneuver).',
    'choking.step4': 'Alternate between 5 blows and 5 thrusts.',
    'choking.step5': 'Call emergency services if they lose consciousness.',
    // Snake Bite
    'snake-bite.step1': 'Move away from the snake.',
    'snake-bite.step2': 'Keep the person calm and still.',
    'snake-bite.step3': 'Keep the bite area below heart level.',
    'snake-bite.step4': 'Clean the wound but do not use water pressure.',
    'snake-bite.step5': 'Do not use a tourniquet or suck the venom.',
    // Bleeding Tips/Warnings
    'bleeding.tip1': 'Use sterile dressings if available.',
    'bleeding.tip2': 'Calm the victim to lower heart rate.',
    'bleeding.warning1': 'Do not remove embedded objects.',
    'bleeding.warning2': 'Do not apply a tourniquet unless trained.',
    // Burns Tips/Warnings
    'burns.tip1': 'Use lukewarm water, not freezing cold.',
    'burns.tip2': 'Keep the person warm elsewhere to prevent shock.',
    'burns.warning1': 'No ice: it can damage tissue.',
    'burns.warning2': 'No ointments or home remedies on fresh burns.',
    // CPR Tips/Warnings
    'cpr.tip1': 'Push down at least 2 inches.',
    'cpr.tip2': 'Allow the chest to recoil completely between compressions.',
    'cpr.warning1': 'Avoid pauses in compressions.',
    'cpr.warning2': 'Only perform rescue breaths if you are trained and comfortable.',
    // Fractures Tips/Warnings
    'fractures.tip1': 'Immobilize the joints above and below the break.',
    'fractures.tip2': 'Check for pulse below the injury site.',
    'fractures.warning1': 'Don\'t try to realign the bone.',
    'fractures.warning2': 'Don\'t give the person anything to eat or drink in case surgery is needed.',
    // Choking Tips/Warnings
    'choking.tip1': 'Stand behind the person for thrusts.',
    'choking.tip2': 'If the person is pregnant or large, perform chest thrusts instead.',
    'choking.warning1': 'Don\'t perform a blind finger sweep.',
    'choking.warning2': 'Don\'t give water or food to a choking person.',
    // Snake Bite Tips/Warnings
    'snake-bite.tip1': 'Try to remember the color and shape of the snake.',
    'snake-bite.tip2': 'Restrict movement of the limb.',
    'snake-bite.warning1': 'No alcohol or caffeine.',
    'snake-bite.warning2': 'Do not try to catch the snake.',
    'note': 'Note',
    'sosNote': 'False alerts may lead to penalties. Use SOS only in life-threatening situations.',
    'locationError': 'Unable to retrieve location. Please check permissions.',
    'locationUnsupported': 'Geolocation is not supported by this browser.',
    'alertSent': 'EMERGENCY ALERT SENT',
    'alertSentDesc': 'Emergency contacts have been notified with your current location.',
    'noVoice': 'Native voice not found on device. Using default.',
  },
  hi: {
    home: 'होम',
    firstAid: 'प्राथमिक उपचार',
    sos: 'आपातकालीन',
    profile: 'प्रोफ़ाइल',
    contacts: 'संपर्क',
    settings: 'सेटिंग्स',
    emergencyResponse: 'आपातकालीन प्रतिक्रिया',
    quickResponse: 'त्वरित प्रतिक्रिया',
    whatSituation: 'क्या स्थिति है?',
    medicalProfile: 'मेडिकल प्रोफ़ाइल',
    healthRecords: 'आपका स्वास्थ्य रिकॉर्ड',
    sosPanel: 'आपातकालीन पैनल',
    assistanceNeeded: 'क्या तत्काल सहायता की आवश्यकता है?',
    callAmbulance: 'एम्बुलेंस',
    callPolice: 'पुलिस',
    callFire: 'अग्निशमन दल',
    shareLocation: 'स्थान साझा करें',
    sendAlert: 'अलर्ट भेजें',
    emergencyTips: 'आपातकालीन सुझाव',
    criticalWarnings: 'महत्वपूर्ण चेतावनी',
    readAloud: 'जोर से पढ़ें',
    stop: 'रुकें',
    saveProfile: 'प्रोफ़ाइल सहेजें',
    bloodGroup: 'रक्त समूह',
    allergies: 'एलर्जी',
    medications: 'दवाइयां',
    conditions: 'चिकित्सा स्थितियां',
    language: 'भाषा',
    darkMode: 'डार्क मोड',
    voiceAssistance: 'आवाज सहायता',
    notifications: 'सूचनाएं',
    restart: 'पुनः आरंभ करें',
    firstAidGuide: 'प्राथमिक उपचार गाइड',
    selectCategory: 'निर्देशों के लिए एक श्रेणी चुनें',
    steps: 'कदम',
    holdToAlert: 'अलर्ट करने के लिए दबाए रखें',
    profileSub: 'प्रथम उत्तरदाताओं के लिए महत्वपूर्ण जानकारी',
    personalDetails: 'व्यक्तिगत विवरण',
    fullName: 'पूरा नाम',
    dob: 'जन्म तिथि',
    medicalInfo: 'चिकित्सा जानकारी',
    securityMessage: 'डेटा एन्क्रिप्ट किया गया है और केवल आपके डिवाइस पर स्थानीय रूप से संग्रहीत है।',
    emergencyHelp: 'आपातकालीन सहायता',
    emergencyHelpSub: 'तत्काल सहायता के लिए नीचे पट्टी पर SOS बटन दबाएं या अधिकारियों को कॉल करने के लिए SOS पैनल पर जाएं।',
    profileSaved: 'प्रोफ़ाइल सफलतापूर्वक सहेजी गई',
    emergencyStored: 'आपातकालीन चिकित्सा जानकारी अब स्थानीय रूप से संग्रहीत है।',
    holdToAlertSub: 'अलर्ट करने के लिए दबाए रखें',
    // First Aid Titles
    'title.bleeding': 'रक्तस्राव',
    'title.burns': 'जलन',
    'title.fractures': 'हड्डी टूटना',
    'title.cpr': 'सीपीआर',
    'title.choking': 'दम घुटना',
    'title.snake-bite': 'सांप का काटना',
    // Bleeding
    'bleeding.step1': 'शांत रहें और यदि उपलब्ध हो तो दस्ताने पहनें।',
    'bleeding.step2': 'साफ कपड़े या पट्टी का उपयोग करके सीधा दबाव डालें।',
    'bleeding.step3': 'यदि संभव हो तो घायल क्षेत्र को हृदय के स्तर से ऊपर उठाएं।',
    'bleeding.step4': 'भीगी हुई पट्टियों को न निकालें, एक और परत जोड़ें।',
    'bleeding.step5': 'यदि रक्तस्राव जारी रहता है तो आपातकालीन सेवाओं को कॉल करें।',
    // Burns
    'burns.step1': 'गर्मी के स्रोत से दूर हटें।',
    'burns.step2': '20 मिनट तक बहते पानी के नीचे जलन को ठंडा करें।',
    'burns.step3': 'तंग गहने सावधानी से निकालें।',
    'burns.step4': 'बाँझ नॉन-स्टिक ड्रेसिंग के साथ कवर करें।',
    'burns.step5': 'बर्फ, मक्खन या टूथपेस्ट न लगाएं।',
    // CPR
    'cpr.step1': 'प्रतिक्रिया की जाँच करें।',
    'cpr.step2': 'आपातकालीन सेवाओं को कॉल करें।',
    'cpr.step3': 'हाथों को छाती के बीच में रखें।',
    'cpr.step4': 'जोर से और तेजी से धक्का दें, 100 से 120 संपीड़न प्रति मिनट।',
    'cpr.step5': 'सहायता आने तक जारी रखें।',
    // Fractures
    'fractures.step1': 'घायल व्यक्ति को तब तक न हिलाएं जब तक आवश्यक न हो।',
    'fractures.step2': 'दबाव डालकर किसी भी रक्तस्राव को रोकें।',
    'fractures.step3': 'यदि संभव हो तो पट्टी के साथ क्षेत्र को स्थिर करें।',
    'fractures.step4': 'सूजन कम करने के लिए बर्फ के पैक लगाएं।',
    'fractures.step5': 'तुरंत पेशेवर चिकित्सा सहायता लें।',
    // Choking
    'choking.step1': 'उन्हें खाँसने के लिए प्रोत्साहित करें।',
    'choking.step2': 'कंधों के बीच 5 बार पीठ पर वार करें।',
    'choking.step3': '5 बार पेट पर धक्का दें (हेमलिच पैंतरेबाज़ी)।',
    'choking.step4': '5 वार और 5 धक्के के बीच बारी-बारी से करें।',
    'choking.step5': 'यदि वे बेहोश हो जाते हैं तो आपातकालीन सेवाओं को कॉल करें।',
    // Snake Bite
    'snake-bite.step1': 'सांप से दूर हटें।',
    'snake-bite.step2': 'व्यक्ति को शांत और स्थिर रखें।',
    'snake-bite.step3': 'काटने वाले क्षेत्र को हृदय के स्तर से नीचे रखें।',
    'snake-bite.step4': 'घाव को साफ करें लेकिन पानी के दबाव का उपयोग न करें।',
    'snake-bite.step5': 'टूर्निकेट का उपयोग न करें या जहर न चूसें।',
    // Bleeding Tips/Warnings
    'bleeding.tip1': 'यदि उपलब्ध हो तो स्टेराइल ड्रेसिंग का उपयोग करें।',
    'bleeding.tip2': 'हृदय गति कम करने के लिए पीड़ित को शांत करें।',
    'bleeding.warning1': 'धंसी हुई वस्तुओं को न निकालें।',
    'bleeding.warning2': 'जब तक प्रशिक्षित न हों, टॉर्निकेट न लगाएं।',
    // Burns Tips/Warnings
    'burns.tip1': 'गुनगुने पानी का उपयोग करें, बर्फीले ठंडे पानी का नहीं।',
    'burns.tip2': 'सदमे को रोकने के लिए व्यक्ति को कहीं और गर्म रखें।',
    'burns.warning1': 'बर्फ नहीं: यह ऊतकों को नुकसान पहुंचा सकती है।',
    'burns.warning2': 'ताजा जलने पर मलहम या घरेलू उपचार न लगाएं।',
    // CPR Tips/Warnings
    'cpr.tip1': 'कम से कम 2 इंच नीचे दबाएं।',
    'cpr.tip2': 'दबाव के बीच छाती को पूरी तरह वापस आने दें।',
    'cpr.warning1': 'दबाव में ठहराव से बचें।',
    'cpr.warning2': 'केवल तभी बचाव सांसें दें जब आप प्रशिक्षित और सहज हों।',
    // Fractures Tips/Warnings
    'fractures.tip1': 'टूटने के ऊपर और नीचे के जोड़ों को स्थिर करें।',
    'fractures.tip2': 'चोट वाली जगह के नीचे नाड़ी की जाँच करें।',
    'fractures.warning1': 'हड्डी को पुन: संरेखित करने का प्रयास न करें।',
    'fractures.warning2': 'सर्जरी की आवश्यकता होने पर व्यक्ति को कुछ भी खाने या पीने को न दें।',
    // Choking Tips/Warnings
    'choking.tip1': 'धक्के देने के लिए व्यक्ति के पीछे खड़े हों।',
    'choking.tip2': 'यदि व्यक्ति गर्भवती या बड़ा है, तो इसके बजाय छाती पर धक्का दें।',
    'choking.warning1': 'आंख मूंदकर उंगली से सफाई न करें।',
    'choking.warning2': 'दम घुटने वाले व्यक्ति को पानी या भोजन न दें।',
    // Snake Bite Tips/Warnings
    'snake-bite.tip1': 'सांप के रंग और आकार को याद रखने की कोशिश करें।',
    'snake-bite.tip2': 'अंग की गति को नियंत्रित करें।',
    'snake-bite.warning1': 'शराब या कैफीन नहीं।',
    'snake-bite.warning2': 'सांप को पकड़ने की कोशिश न करें।',
    'note': 'नोट',
    'sosNote': 'गलत अलर्ट पर जुर्माना लगाया जा सकता है। केवल जीवन के लिए खतरनाक स्थितियों में ही आपातकालीन अलर्ट (SOS) का उपयोग करें।',
    'locationError': 'स्थान प्राप्त करने में असमर्थ। कृपया अनुमतियां जांचें।',
    'locationUnsupported': 'इस ब्राउज़र द्वारा जियोलोकेशन समर्थित नहीं है।',
    'alertSent': 'आपातकालीन अलर्ट भेजा गया',
    'alertSentDesc': 'आपातकालीन संपर्कों को आपके वर्तमान स्थान के साथ सूचित कर दिया गया है।',
    'noVoice': 'डिवाइस पर मूल आवाज़ नहीं मिली। डिफॉल्ट का उपयोग किया जा रहा है।',
  },
  kn: {
    home: 'ಮನೆ',
    firstAid: 'ಪ್ರಥಮ ಚಿಕಿತ್ಸೆ',
    sos: 'ತುರ್ತು',
    profile: 'ಪ್ರೊಫೈಲ್',
    contacts: 'ಸಂಪರ್ಕಗಳು',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    emergencyResponse: 'ತುರ್ತು ಪ್ರತಿಕ್ರಿಯೆ',
    quickResponse: 'ತ್ವರಿತ ಪ್ರತಿಕ್ರಿಯೆ',
    whatSituation: 'ಪರಿಸ್ಥಿತಿ ಏನು?',
    medicalProfile: 'ವೈದ್ಯಕೀಯ ಪ್ರೊಫೈಲ್',
    healthRecords: 'ನಿಮ್ಮ ಆರೋಗ್ಯ ದಾಖಲೆಗಳು',
    sosPanel: 'ತುರ್ತು ಫಲಕ',
    assistanceNeeded: 'ತಕ್ಷಣದ ಸಹಾಯ ಬೇಕೇ?',
    callAmbulance: 'ಅಂಬ್ಯುಲೆನ್ಸ್',
    callPolice: 'ಪೊಲೀಸ್',
    callFire: 'ಅಗ್ನಿಶಾಮಕ ದಳ',
    shareLocation: 'ಸ್ಥಳ ಹಂಚಿಕೊಳ್ಳಿ',
    sendAlert: 'ಎಚ್ಚರಿಕೆ ಕಳುಹಿಸಿ',
    emergencyTips: 'ತುರ್ತು ಸಲಹೆಗಳು',
    criticalWarnings: 'ನಿರ್ಣಾಯಕ ಎಚ್ಚರಿಕೆಗಳು',
    readAloud: 'ಜೋರಾಗಿ ಓದಿ',
    stop: 'ನಿಲ್ಲಿಸಿ',
    saveProfile: 'ಪ್ರೊಫೈಲ್ ಉಳಿಸಿ',
    bloodGroup: 'ರಕ್ತದ ಗುಂಪು',
    allergies: 'ಅಲರ್ಜಿಗಳು',
    medications: 'ಔಷಧಿಗಳು',
    conditions: 'ವೈದ್ಯಕೀಯ ಸ್ಥಿತಿಗಳು',
    language: 'ಭಾಷೆ',
    darkMode: 'ಡಾರ್ಕ್ ಮೋಡ್',
    voiceAssistance: 'ಧ್ವನಿ ಸಹಾಯ',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    restart: 'ಮತ್ತೆ ಪ್ರಾರಂಭಿಸಿ',
    firstAidGuide: 'ಪ್ರಥಮ ಚಿಕಿತ್ಸಾ ಮಾರ್ಗಸೂಚಿ',
    selectCategory: 'ಸೂಚನೆಗಳಿಗಾಗಿ ವಿಭಾಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    steps: 'ಹಂತಗಳು',
    holdToAlert: 'ಎಚ್ಚರಿಸಲು ಒತ್ತಿ ಹಿಡಿಯಿರಿ',
    profileSub: 'ತುರ್ತು ಪ್ರತಿಕ್ರಿಯೆ ನೀಡುವವರಿಗೆ ಪ್ರಮುಖ ಮಾಹಿತಿ',
    personalDetails: 'ವೈಯಕ್ತಿಕ ವಿವರಗಳು',
    fullName: 'ಪೂರ್ಣ ಹೆಸರು',
    dob: 'ಹುಟ್ಟಿದ ದಿನಾಂಕ',
    medicalInfo: 'ವೈದ್ಯಕೀಯ ಮಾಹಿತಿ',
    securityMessage: 'ಮಾಹಿತಿಯನ್ನು ಎನ್‌ಕ್ರಿಪ್ಟ್ ಮಾಡಲಾಗಿದೆ ಮತ್ತು ನಿಮ್ಮ ಸಾಧನದಲ್ಲಿ ಮಾತ್ರ ಸಂಗ್ರಹಿಸಲಾಗಿದೆ.',
    emergencyHelp: 'ತುರ್ತು ಸಹಾಯ',
    emergencyHelpSub: 'ತಕ್ಷಣದ ಸಹಾಯಕ್ಕಾಗಿ ಕೆಳಗಿನ SOS ಬಟನ್ ಒತ್ತಿರಿ ಅಥವಾ ಅಧಿಕಾರಿಗಳಿಗೆ ಕರೆ ಮಾಡಲು SOS ಫಲಕಕ್ಕೆ ಭೇಟಿ ನೀಡಿ.',
    profileSaved: 'ಪ್ರೊಫೈಲ್ ಯಶಸ್ವಿಯಾಗಿ ಉಳಿಸಲಾಗಿದೆ',
    emergencyStored: 'ತುರ್ತು ವೈದ್ಯಕೀಯ ಮಾಹಿತಿಯನ್ನು ಈಗ ಸ್ಥಳೀಯವಾಗಿ ಸಂಗ್ರಹಿಸಲಾಗಿದೆ.',
    holdToAlertSub: 'ಎಚ್ಚರಿಸಲು ಒತ್ತಿ ಹಿಡಿಯಿರಿ',
    // First Aid Titles
    'title.bleeding': 'ರಕ್ತಸ್ರಾವ',
    'title.burns': 'ಸುಟ್ಟ ಗಾಯ',
    'title.fractures': 'ಮೂಳೆ ಮುರಿತ',
    'title.cpr': 'ಸಿಪಿಆರ್',
    'title.choking': 'ಉಸಿರುಗಟ್ಟುವಿಕೆ',
    'title.snake-bite': 'ಹಾವು ಕಚ್ಚುವಿಕೆ',
    // Bleeding
    'bleeding.step1': 'ಶಾಂತವಾಗಿರಿ ಮತ್ತು ಲಭ್ಯವಿದ್ದಲ್ಲಿ ಕೈಗವಸುಗಳನ್ನು ಧರಿಸಿ.',
    'bleeding.step2': 'ಶುಚಿಯಾದ ಬಟ್ಟೆ ಅಥವಾ ಬ್ಯಾಂಡೇಜ್ ಬಳಸಿ ನೇರ ಒತ್ತಡವನ್ನು ಹಾಕಿ.',
    'bleeding.step3': 'ಸಾಧ್ಯವಾದರೆ ಗಾಯಗೊಂಡ ಭಾಗವನ್ನು ಹೃದಯದ ಮಟ್ಟಕ್ಕಿಂತ ಮೇಲೆ ಎತ್ತಿ.',
    'bleeding.step4': 'ನೆನೆದ ಬ್ಯಾಂಡೇಜ್‌ಗಳನ್ನು ತೆಗೆಯಬೇಡಿ, ಇನ್ನೊಂದು ಪದರವನ್ನು ಸೇರಿಸಿ.',
    'bleeding.step5': 'ರಕ್ತಸ್ರಾವ ಮುಂದುವರಿದರೆ ತುರ್ತು ಸೇವೆಗಳಿಗೆ ಕರೆ ಮಾಡಿ.',
    // Burns
    'burns.step1': 'ಶಾಖದ ಮೂಲದಿಂದ ದೂರ ಸರಿಯಿರಿ.',
    'burns.step2': '20 ನಿಮಿಷಗಳ ಕಾಲ ಹರಿಯುವ ನೀರಿನಲ್ಲಿ ಸುಟ್ಟ ಗಾಯವನ್ನು ತಂಪಾಗಿಸಿ.',
    'burns.step3': 'ಬಿಗಿಯಾದ ಆಭರಣಗಳನ್ನು ಎಚ್ಚರಿಕೆಯಿಂದ ತೆಗೆದುಹಾಕಿ.',
    'burns.step4': 'ಕ್ರಿಮಿಮುಕ್ತ ಅಂಟಿಕೊಳ್ಳದ ಬ್ಯಾಂಡೇಜ್‌ನಿಂದ ಮುಚ್ಚಿ.',
    'burns.step5': 'ಐಸ್ ಅಥವಾ ಬೆಣ್ಣೆ ಹಚ್ಚಬೇಡಿ.',
    // CPR
    'cpr.step1': 'ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ಪರಿಶೀಲಿಸಿ.',
    'cpr.step2': 'ತುರ್ತು ಸೇವೆಗಳಿಗೆ ಕರೆ ಮಾಡಿ.',
    'cpr.step3': 'ಎದೆಯ ಮಧ್ಯಭಾಗದಲ್ಲಿ ಕೈಗಳನ್ನು ಇರಿಸಿ.',
    'cpr.step4': 'ನಿಮಿಷಕ್ಕೆ 100 ರಿಂದ 120 ಬಾರಿ ಎದೆಯನ್ನು ವೇಗವಾಗಿ ಒತ್ತಿ.',
    'cpr.step5': 'ಸಹಾಯ ಬರುವವರೆಗೆ ಮುಂದುವರಿಸಿ.',
    // Fractures
    'fractures.step1': 'ಅಗತ್ಯವಿಲ್ಲದಿದ್ದರೆ ಗಾಯಗೊಂಡ ವ್ಯಕ್ತಿಯನ್ನು ಚಲಿಸಬೇಡಿ.',
    'fractures.step2': 'ಒತ್ತಡವನ್ನು ಹಾಕುವ ಮೂಲಕ ರಕ್ತಸ್ರಾವವನ್ನು ನಿಲ್ಲಿಸಿ.',
    'fractures.step3': 'ಸಾಧ್ಯವಾದರೆ ಸ್ಪ್ಲಿಂಟ್ ಬಳಸಿ ಗಾಯಗೊಂಡ ಜಾಗವನ್ನು ಅಲುಗಾಡದಂತೆ ಮಾಡಿ.',
    'fractures.step4': 'ಊತವನ್ನು ಕಡಿಮೆ ಮಾಡಲು ಐಸ್ ಪ್ಯಾಕ್ ಹಚ್ಚಿ.',
    'fractures.step5': 'ತಕ್ಷಣ ವೃತ್ತಿಪರ ವೈದ್ಯಕೀಯ ಸಹಾಯವನ್ನು ಪಡೆಯಿರಿ.',
    // Choking
    'choking.step1': 'ಕೆಮ್ಮಲು ಅವರನ್ನು ಪ್ರೋತ್ಸಾಹಿಸಿ.',
    'choking.step2': 'ಬೆನ್ನಿನ ಮಧ್ಯಭಾಗದಲ್ಲಿ 5 ಬಾರಿ ಜೋರಾಗಿ ತಟ್ಟಿರಿ.',
    'choking.step3': '5 ಬಾರಿ ಕಿಬ್ಬೊಟ್ಟೆಯ ತಳ್ಳುವಿಕೆಗಳನ್ನು ನೀಡಿ (ಹೈಮ್ಲಿಚ್ ತಂತ್ರ).',
    'choking.step4': '5 ಏಟುಗಳು ಮತ್ತು 5 ತಳ್ಳುವಿಕೆಗಳ ನಡುವೆ ಪರ್ಯಾಯವಾಗಿ ಮಾಡಿ.',
    'choking.step5': 'ಅವರು ಪ್ರಜ್ಞೆ ತಪ್ಪಿದರೆ ತುರ್ತು ಸೇವೆಗಳಿಗೆ ಕರೆ ಮಾಡಿ.',
    // Snake Bite
    'snake-bite.step1': 'ಹಾವಿನಿಂದ ದೂರ ಸರಿಯಿರಿ.',
    'snake-bite.step2': 'ವ್ಯಕ್ತಿಯನ್ನು ಶಾಂತವಾಗಿ ಮತ್ತು ಅಲುಗಾಡದಂತೆ ಇರಿಸಿ.',
    'snake-bite.step3': 'ಕಚ್ಚಿದ ಜಾಗವನ್ನು ಹೃದಯದ ಮಟ್ಟಕ್ಕಿಂತ ಕೆಳಗೆ ಇರಿಸಿ.',
    'snake-bite.step4': 'ಗಾಯವನ್ನು ಸ್ವಚ್ಛಗೊಳಿಸಿ ಆದರೆ ನೀರಿನ ಒತ್ತಡವನ್ನು ಬಳಸಬೇಡಿ.',
    'snake-bite.step5': 'ಟೂರ್ನಿಕೆಟ್ ಬಳಸಬೇಡಿ ಅಥವಾ ವಿಷವನ್ನು ಹೀರಬೇಡಿ.',
    // Bleeding Tips/Warnings
    'bleeding.tip1': 'ಲಭ್ಯವಿದ್ದಲ್ಲಿ ಸ್ಟೆರೈಲ್ ಡ್ರೆಸ್ಸಿಂಗ್ ಬಳಸಿ.',
    'bleeding.tip2': 'ಹೃದಯ ಬಡಿತವನ್ನು ಕಡಿಮೆ ಮಾಡಲು ಸಂತ್ರಸ್ತನನ್ನು ಶಾಂತಗೊಳಿಸಿ.',
    'bleeding.warning1': 'ಒಳಗೆ ಸಿಲುಕಿರುವ ವಸ್ತುಗಳನ್ನು ತೆಗೆಯಬೇಡಿ.',
    'bleeding.warning2': 'ತರಬೇತಿ ಪಡೆಯದ ಹೊರತು ಟೂರ್ನಿಕೆಟ್ ಬಳಸಬೇಡಿ.',
    // Burns Tips/Warnings
    'burns.tip1': 'ಉಗುರು ಬೆಚ್ಚಗಿನ ನೀರನ್ನು ಬಳಸಿ, ಅತಿ ತಣ್ಣಗಿನ ನೀರನ್ನಲ್ಲ.',
    'burns.tip2': 'ಶಾಕ್ ತಡೆಗಟ್ಟಲು ವ್ಯಕ್ತಿಯನ್ನು ಬೆಚ್ಚಗೆ ಇರಿಸಿ.',
    'burns.warning1': 'ಐಸ್ ಬಳಸಬೇಡಿ: ಇದು ಪೆಟ್ಟಾದ ಜಾಗಕ್ಕೆ ಹಾನಿ ಮಾಡಬಹುದು.',
    'burns.warning2': 'ಹೊಸ ಸುಟ್ಟ ಗಾಯಗಳಿಗೆ ಮುಲಾಮುಗಳನ್ನು ಹಚ್ಚಬೇಡಿ.',
    // CPR Tips/Warnings
    'cpr.tip1': 'ಕನಿಷ್ಠ 2 ಇಂಚು ಆಳಕ್ಕೆ ಒತ್ತಿ.',
    'cpr.tip2': 'ಒತ್ತುವ ನಡುವೆ ಎದೆಯು ಸಂಪೂರ್ಣವಾಗಿ ಹಿಂದಕ್ಕೆ ಬರಲು ಬಿಡಿ.',
    'cpr.warning1': 'ಎದೆಯನ್ನು ಒತ್ತುವ ನಡುವೆ ವಿರಾಮಗಳನ್ನು ತಪ್ಪಿಸಿ.',
    'cpr.warning2': 'ನೀವು ತರಬೇತಿ ಪಡೆದಿದ್ದರೆ ಮಾತ್ರ ಉಸಿರಾಟವನ್ನು ನೀಡಿ.',
    // Fractures Tips/Warnings
    'fractures.tip1': 'ಮುರಿತದ ಮೇಲಿನ ಮತ್ತು ಕೆಳಗಿನ ಕೀಲುಗಳನ್ನು ಅಲುಗಾಡದಂತೆ ಮಾಡಿ.',
    'fractures.tip2': 'ಗಾಯದ ಕೆಳಗೆ ನಾಡಿ ಬಡಿತವನ್ನು ಪರೀಕ್ಷಿಸಿ.',
    'fractures.warning1': 'ಮೂಳೆಯನ್ನು ಸರಿಹೊಂದಿಸಲು ಪ್ರಯತ್ನಿಸಬೇಡಿ.',
    'fractures.warning2': 'ಶಸ್ತ್ರಚಿಕಿತ್ಸೆ ಅಗತ್ಯವಿರಬಹುದಾದ ಕಾರಣ ವ್ಯಕ್ತಿಗೆ ಏನನ್ನೂ ತಿನ್ನಲು ಅಥವಾ ಕುಡಿಯಲು ಕೊಡಬೇಡಿ.',
    // Choking Tips/Warnings
    'choking.tip1': 'ತಳ್ಳಲು ವ್ಯಕ್ತಿಯ ಹಿಂದೆ ನಿಂತುಕೊಳ್ಳಿ.',
    'choking.tip2': 'ವ್ಯಕ್ತಿಯು ಗರ್ಭಿಣಿಯಾಗಿದ್ದರೆ ಅಥವಾ ದಪ್ಪವಾಗಿದ್ದರೆ, ಎದೆಯ ತಳ್ಳುವಿಕೆಗಳನ್ನು ನೀಡಿ.',
    'choking.warning1': 'ಬೆರಳುಗಳಿಂದ ಬಾಯಿಯೊಳಗೆ ಕಸವನ್ನು ಹುಡುಕಬೇಡಿ.',
    'choking.warning2': 'ಉಸಿರುಗಟ್ಟುವ ವ್ಯಕ್ತಿಗೆ ನೀರು ಅಥವಾ ಆಹಾರವನ್ನು ನೀಡಬೇಡಿ.',
    // Snake Bite Tips/Warnings
    'snake-bite.tip1': 'ಹಾವಿನ ಬಣ್ಣ ಮತ್ತು ಆಕಾರವನ್ನು ನೆನಪಿಟ್ಟುಕೊಳ್ಳಲು ಪ್ರಯತ್ನಿಸಿ.',
    'snake-bite.tip2': 'ಗಾಯಗೊಂಡ ಅಂಗದ ಚಲನೆಯನ್ನು ನಿರ್ಬಂಧಿಸಿ.',
    'snake-bite.warning1': 'ಮದ್ಯ ಅಥವಾ ಕೆಫೀನ್ ನೀಡಬೇಡಿ.',
    'snake-bite.warning2': 'ಹಾವನ್ನು ಹಿಡಿಯಲು ಪ್ರಯತ್ನಿಸಬೇಡಿ.',
    'note': 'ಸೂಚನೆ',
    'sosNote': 'ಸುಳ್ಳು ಎಚ್ಚರಿಕೆಗಳು ದಂಡಕ್ಕೆ ಕಾರಣವಾಗಬಹುದು. ಜೀವಕ್ಕೆ ಅಪಾಯವಿರುವ ಸಂದರ್ಭಗಳಲ್ಲಿ ಮಾತ್ರ SOS ಬಳಸಿ.',
    'locationError': 'ಸ್ಥಳವನ್ನು ಹಿಂಪಡೆಯಲು ಸಾಧ್ಯವಿಲ್ಲ. ದಯವಿಟ್ಟು ಅನುಮತಿಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.',
    'locationUnsupported': 'ಈ ಬ್ರೌಸರ್‌ನಲ್ಲಿ ಜಿಯೋಲೊಕೇಶನ್ ಬೆಂಬಲಿತವಾಗಿಲ್ಲ.',
    'alertSent': 'ತುರ್ತು ಎಚ್ಚರಿಕೆ ಕಳುಹಿಸಲಾಗಿದೆ',
    'alertSentDesc': 'ನಿಮ್ಮ ಪ್ರಸ್ತುತ ಸ್ಥಳದೊಂದಿಗೆ ತುರ್ತು ಸಂಪರ್ಕಗಳಿಗೆ ತಿಳಿಸಲಾಗಿದೆ.',
    'noVoice': 'ನಿಮ್ಮ ಸಾಧನದಲ್ಲಿ ಕನ್ನಡದ ಧ್ವನಿ ಲಭ್ಯವಿಲ್ಲ. ದಯವಿಟ್ಟು ಸಾಧನದ ಸೆಟ್ಟಿಂಗ್ಸ್‌ನಲ್ಲಿ ಕನ್ನಡ ಧ್ವನಿಯನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ.',
  },
  es: {
    home: 'Inicio',
    firstAid: 'Primeros Auxilios',
    sos: 'SOS',
    profile: 'Perfil',
    contacts: 'Contactos',
    settings: 'Ajustes',
    emergencyResponse: 'RESPUESTA DE EMERGENCIA',
    quickResponse: 'RESPUESTA RÁPIDA',
    whatSituation: '¿Cuál es la situación?',
    medicalProfile: 'Perfil Médico',
    healthRecords: 'Tus registros de salud',
    sosPanel: 'PANEL SOS',
    assistanceNeeded: '¿Necesita asistencia inmediata?',
    callAmbulance: 'Ambulancia',
    callPolice: 'Policía',
    callFire: 'Bomberos',
    shareLocation: 'Compartir ubicación',
    sendAlert: 'Enviar alerta',
    emergencyTips: 'Consejos de emergencia',
    criticalWarnings: 'ADVERTENCIAS CRÍTICAS',
    readAloud: 'LEER EN VOZ ALTA',
    stop: 'PARAR',
    saveProfile: 'Guardar perfil',
    bloodGroup: 'Grupo sanguíneo',
    allergies: 'Alergias',
    medications: 'Medicamentos',
    conditions: 'Condiciones médicas',
    language: 'Idioma',
    darkMode: 'Modo oscuro',
    voiceAssistance: 'Asistencia de voz',
    notifications: 'Notificaciones',
    restart: 'REINICIAR',
    firstAidGuide: 'Guía de primeros auxilios',
    selectCategory: 'Seleccione una categoría para instrucciones',
    steps: 'Pasos',
    holdToAlert: 'Mantener para alertar',
    profileSub: 'Información vital para socorristas',
    personalDetails: 'Detalles personales',
    fullName: 'Nombre completo',
    dob: 'Fecha de nacimiento',
    medicalInfo: 'Información médica',
    securityMessage: 'Los datos están encriptados y almacenados localmente solo en su dispositivo.',
    emergencyHelp: 'Ayuda de emergencia',
    emergencyHelpSub: 'Presione el botón SOS en la barra inferior para asistencia inmediata o visite el panel SOS para llamar a las autoridades.',
    profileSaved: 'Perfil guardado con éxito',
    emergencyStored: 'La información médica de emergencia ahora se almacena localmente.',
    holdToAlertSub: 'Mantener para alertar',
    // First Aid Titles
    'title.bleeding': 'Sangrado',
    'title.burns': 'Quemaduras',
    'title.fractures': 'Fracturas',
    'title.cpr': 'RCP',
    'title.choking': 'Atragantamiento',
    'title.snake-bite': 'Mordedura de serpiente',
    // Bleeding
    'bleeding.step1': 'Mantenga la calma y use guantes si están disponibles.',
    'bleeding.step2': 'Aplique presión directa con un paño limpio o vendaje.',
    'bleeding.step3': 'Eleve el área lesionada por encima del nivel del corazón.',
    'bleeding.step4': 'No quite los vendajes empapados, añada otra capa.',
    'bleeding.step5': 'Llame a emergencias si el sangrado continúa.',
    // Burns
    'burns.step1': 'Aléjese de la fuente de calor.',
    'burns.step2': 'Enfríe la quemadura bajo agua corriente por 20 minutos.',
    'burns.step3': 'Quítese las joyas apretadas con cuidado.',
    'burns.step4': 'Cubra con un vendaje estéril no adherente.',
    'burns.step5': 'No aplique hielo, mantequilla o pasta de dientes.',
    // CPR
    'cpr.step1': 'Verifique la capacidad de respuesta.',
    'cpr.step2': 'Llame a los servicios de emergencia.',
    'cpr.step3': 'Coloque las manos en el centro del pecho.',
    'cpr.step4': 'Empuje fuerte y rápido, de 100 a 120 compresiones por minuto.',
    'cpr.step5': 'Continúe hasta que llegue ayuda.',
    // Fractures
    'fractures.step1': 'No mueva a la persona lesionada a menos que sea necesario.',
    'fractures.step2': 'Detenga cualquier sangrado aplicando presión.',
    'fractures.step3': 'Inmovilice el área con una férula si es posible.',
    'fractures.step4': 'Aplique compresas de hielo para limitar la hinchazón.',
    'fractures.step5': 'Busque ayuda médica profesional de inmediato.',
    // Choking
    'choking.step1': 'Anímelos a toser.',
    'choking.step2': 'Dé 5 golpes en la espalda entre las escápulas.',
    'choking.step3': 'Dé 5 compresiones abdominales (maniobra de Heimlich).',
    'choking.step4': 'Alterne entre 5 golpes y 5 compresiones.',
    'choking.step5': 'Llame a emergencias si pierden el conocimiento.',
    // Snake Bite
    'snake-bite.step1': 'Aléjese de la serpiente.',
    'snake-bite.step2': 'Mantenga a la persona tranquila e inmóvil.',
    'snake-bite.step3': 'Mantenga el área de la mordedura por debajo del nivel del corazón.',
    'snake-bite.step4': 'Limpie la herida pero no use presión de agua.',
    'snake-bite.step5': 'No use un torniquete ni succione el veneno.',
    // Bleeding Tips/Warnings
    'bleeding.tip1': 'Use apósitos estériles si están disponibles.',
    'bleeding.tip2': 'Calme a la víctima para reducir el ritmo cardíaco.',
    'bleeding.warning1': 'No retire objetos incrustados.',
    'bleeding.warning2': 'No aplique un torniquete a menos que esté capacitado.',
    // Burns Tips/Warnings
    'burns.tip1': 'Use agua tibia, no helada.',
    'burns.tip2': 'Mantenga a la persona abrigada para evitar el shock.',
    'burns.warning1': 'Nada de hielo: puede dañar el tejido.',
    'burns.warning2': 'No aplicar pomadas ni remedios caseros en quemaduras recientes.',
    // CPR Tips/Warnings
    'cpr.tip1': 'Empuje hacia abajo al menos 2 pulgadas.',
    'cpr.tip2': 'Permita que el pecho regrese completamente entre compresiones.',
    'cpr.warning1': 'Evite las pausas en las compresiones.',
    'cpr.warning2': 'Solo realice respiraciones de rescate si está capacitado y se siente cómodo.',
    // Fractures Tips/Warnings
    'fractures.tip1': 'Inmovilice las articulaciones por encima y por debajo de la fractura.',
    'fractures.tip2': 'Verifique el pulso por debajo del sitio de la lesión.',
    'fractures.warning1': 'No intente realinear el hueso.',
    'fractures.warning2': 'No le dé a la persona nada de comer o beber por si necesita cirugía.',
    // Choking Tips/Warnings
    'choking.tip1': 'Párese detrás de la persona para realizar las compresiones.',
    'choking.tip2': 'Si la persona está embarazada o es corpulenta, realice compresiones torácicas.',
    'choking.warning1': 'No realice un barrido digital a ciegas.',
    'choking.warning2': 'No dé agua ni comida a una persona que se está asfixiando.',
    // Snake Bite Tips/Warnings
    'snake-bite.tip1': 'Trate de recordar el color y la forma de la serpiente.',
    'snake-bite.tip2': 'Restrinja el movimiento de la extremidad.',
    'snake-bite.warning1': 'Nada de alcohol ni cafeína.',
    'snake-bite.warning2': 'No intente atrapar a la serpiente.',
    'note': 'Nota',
    'sosNote': 'Las falsas alertas pueden dar lugar a sanciones. Utilice el SOS solo en situaciones que pongan en peligro su vida.',
    'locationError': 'No se pudo obtener la ubicación. Por favor, compruebe los permisos.',
    'locationUnsupported': 'La geolocalización no es compatible con este navegador.',
    'alertSent': 'ALERTA DE EMERGENCIA ENVIADA',
    'alertSentDesc': 'Los contactos de emergencia han sido notificados con su ubicación actual.',
    'noVoice': 'No se encontró una voz nativa en el dispositivo. Usando por defecto.',
  }
};

const locales: Record<Language, string> = {
  en: 'en-US',
  hi: 'hi-IN',
  kn: 'kn-IN',
  es: 'es-ES'
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app_language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || translations['en'][key] || key;
  };

  const getLocale = () => locales[language];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, getLocale }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
